### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-final-MarinaCouso#1]
Muy buen trabajo @Marinulis !!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 355 / 473
- [ ] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./assets/css/`.
- [ ] HTML > ATRIBUTOS: Todos los `a` deben tener el atributo `title`.
- [ ] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [ ] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.
- [ ] HTML > HERO: Debe haber un `a` o un `button` dentro del hero.
- [ ] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un `H2 - H6`.
- [ ] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "3 Reasons To Purchase" que sea un `H2 - H6`.
- [ ] HTML > MÓDULO 3 REASON: Debe haber un `a` o un `button` con el texto "More reasons".
- [ ] HTML > FOOTER: Debe haber un `a` con el texto "Mastodon.social".
- [ ] HTML > FOOTER: Necesitamos una o dos etiquetas `nav` dentro del `footer`.
- [ ] HTML > FOOTER: Necesitamos dos `ul` dentro de `nav`.

- [ ] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.button.btn-go { padding: 0.5em 1.2em }`
- [ ] CSS > MÓDULO 3 REASONS: En móvil el Grid debe tener 3 filas.
- [ ] CSS > FOOTER: El footer en tablet debe estar maquetado con > `flex-direction: row`.
- [ ] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by MarinaCouso** [comment]
Hola Miguel! 

Muchas gracias por enviarnos con tanta rapidez la valoración del examen. Como ocurrió la otra vez, y veo que hay cosas que no encajan, te paso las notas que he tomado sobre cada uno de los puntos que indicas. Si están correctos me dices y lo corrijo, si no me espero a que los cambies o me digas cómo hacemos. 

----
    • CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./assets/css/.      **Esto ya es así.**
    • HTML > ATRIBUTOS: Todos los a deben tener el atributo title.
      **El único que encuentro es el de la hamburguesa, que se lo puse a la img en vez de a <a>, ¿es incorrecto?**
    • HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un nav. **¿Dónde? ¿Debe rodear a <a>?**
    • HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.  **Esto ya es así, ¿es incorrecto que lo divida en dos <span> para asegurar su alineación?**
    • HTML > HERO: Debe haber un a o un button dentro del hero.
      **¿La diferencia es que le he llamado header en vez de hero? Porque ya tiene un <a>.**
    • HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un H2 – H6.  **¿Es incorrecto que sea un small?**
    • HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "3 Reasons To Purchase" que sea un H2 – H6.
**Este punto no tiene sentido, ese texto está en la siguiente sección. Si es así y corresponde a la siguiente sección, ya existe.**
    • HTML > MÓDULO 3 REASON: Debe haber un a o un button con el texto "More reasons".
      **Ya existe.**
    • HTML > FOOTER: Debe haber un a con el texto "Mastodon.social".
      **Ya existe.**
    • HTML > FOOTER: Necesitamos una o dos etiquetas nav dentro del footer.
    • HTML > FOOTER: Necesitamos dos ul dentro de nav.
      **(Respondiendo a las dos anteriores) Creo que no entiendo muy bien la función de la etiqueta nav porque en las dos ocasiones que lo mencionas no lo puse porque entiendo que no aporta nada, sólo añade una caja vacía que contiene.**
    • CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. .button.btn-go { padding: 0.5em 1.2em }
      **Ok**
    • CSS > MÓDULO 3 REASONS: En móvil el Grid debe tener 3 filas.
      **¿Por qué? No sabía que fuera más correcto eso que usar las 12 que hay por defecto.** 
    • CSS > FOOTER: El footer en tablet debe estar maquetado con > flex-direction: row.
      **Así es como está.**
    • CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > order.
      **Así es como está.**
Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.
Y recuerda algo muy importante: **(entiendo que es un recordatorio genérico, porque creo que se cumple, si no lo miro en detalle).**
    • Escribe tu código en inglés. 
    • Escribe todos los ficheros y carpetas en inglés. 
    • Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo. 
---
¡Gracias!

**Comment by profes-adalab** [comment]
Hola señoría te contesto a la movida:

- CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./assets/css/: efectivamente la ruta está bien, pero el bot se está tostando porque estás cargando `<link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet" />` que no existe. Ha encontrado un error, pero lo ha expresado mal.
- HTML > ATRIBUTOS: Todos los a deben tener el atributo title: como bien dices la haburguesilla no tiene el atributo title. No lo corrijas, está bien así.
- HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un nav: un enlace que consideramos parte de un menú debe tener un nav. Si es un enlace en mitad de un párrafo que va a otra página no lo consideramos un menú, sino un enlace suelto. Debería estar rodeado por un nav.
- HTML > HERO: El texto del título del hero debe ser: Anonymous proxy: tú tienes Anonymous Proxy con la P mayúscula.
-  HTML > HERO: Debe haber un a o un button dentro del hero: tienes más razón que una santa, fallo mío.
- HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un H2 – H6: Es muy subjetivo. Déjalo como un small, me parece bien.
- HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "3 Reasons To Purchase" que sea un H2 – H6: Tienes razón me he equivocado de sección. El texto que debe estar en html debería ser "3 reasons to purchase" en minúsculas todo, por eso te canta el error.
- HTML > MÓDULO 3 REASON: Debe haber un a o un button con el texto "More reasons": Tienes más razón que una santa, fallo mío.
- HTML > FOOTER: Debe haber un a con el texto "Mastodon.social": El texto que tienes el html es Mastodon.Social.
- HTML > FOOTER: Necesitamos una o dos etiquetas nav dentro del footer y HTML > FOOTER: Necesitamos dos ul dentro de nav: Si son menús deben tener un nav. Te lo explico en persona mejor.
- CSS > MÓDULO 3 REASONS: En móvil el Grid debe tener 3 filas: ya sabía yo que no me tenía que meter a evaluar el grid, hay muchas opciones y me ha estallado en la cara. Lo tienes bien, no lo cambies.
- CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > order y CSS > FOOTER: El footer en tablet debe estar maquetado con > flex-direction: row.: me has reventado el bot ;) no pensaba que ibas a maquetar el copy con un flex para los small internos. Está bien como lo has hecho.

**Comment by profes-adalab** [comment]
Madre mía, la verdad es que me ha quedado un bot bastante pedante...

**Comment by MarinaCouso** [comment]
@migueldelmazo ya están corregidos los issues pendientes.

**Comment by migueldelmazo** [comment]
Muy buen curro señoría @MarinaCouso !!!
